# Files


---



In [1]:
f = open("test.txt","w")
print(f)

<_io.TextIOWrapper name='test.txt' mode='w' encoding='UTF-8'>


```f``` is the name of defined variable for the .txt file.

```open``` function opens or creates file.

Files have 3 main modes:

 - ```"r"``` read mode

 - ```"w"``` write mode

 - ```"a"``` append mode

In [2]:
f.write("Now is the time")
f.write(" to close the file.")
f.close()

```write()``` function writes into the file.

```close()``` function closes the file.

In [3]:
f = open("test.txt","r")
text = f.read()
print(text)

Now is the time to close the file.


I opened the __"test.txt"__ in read mode, then I read it with using ```read()``` function and assigned to the variable that named with ```text```. Then I printed it.

In [4]:
f = open("test.txt","r")
print(f.read(8))
print(f.read(1000000 + 6))

Now is t
he time to close the file.


 - If you write **8** into ```read()``` function's paranthesis. It will read first **8** digits.
 - If you write **1000000 + 6** into ```read()``` function's paranthesis. It will read all of the file, except first **6** digits.

In [5]:
f1l3 = open("f1l3.txt","w")
f1l3.write("Python is a great language.\n Yeah it's great!\n")
f1l3.close()

In [6]:
f1l3 = open("f1l3.txt","r+")
my_string = f1l3.read(17)
print("Our string is:", my_string)

Our string is: Python is a great


```"r+"``` is **read&write** mode.



In [7]:
position = f1l3.tell()
print("Current file position:", position)

Current file position: 17


```tell()``` function returns the cursor's last position.

In [8]:
position = f1l3.seek(0,0)
my_string = f1l3.read(17)
print("Again our string is:", my_string)

Again our string is: Python is a great


```seek()``` function is sets position of cursor.

# try, except, else, finally


---



In [11]:
try:
  f = open ("test","r")
  f.write("This is my test for exception handling.")
except IOError:
  print("Error: cannot find file or read data")
else:
  print("Written content in the file succesfully.")

Error: cannot find file or read data


In [12]:
try:
  f = open ("test","w")
  f.write("This is my test for exception handling.")
except IOError:
  print("Error: cannot find file or read data")
else:
  print("Written content in the file succesfully.")

Written content in the file succesfully.


In [14]:
try:
  f = open ("test","w")
  f.write("This is my test for exception handling.")
except IOError:
  print("Error: cannot find file or read data")
finally:
  print("Written content in the file succesfully.")

Written content in the file succesfully.


  - ```try``` is executes the code inside.
  - if ```try``` does not work successfully, it executes the code inside of ```except```.
  - if ```try``` works successfully, it executes the code inside of ```else```.
  - ```finally``` works whether ```try``` works or not.

# Dictionaries

---

In [15]:
dict = {'Name':'Osman', 'Age':'2', 'Class':'Graduated'}
dict['Age'] = 24
dict['School'] = 'AYBU'
print(dict['Age'])
print(dict['School'])

24
AYBU


In [21]:
dict = {'Name':'Osman', 'Age':'24', 'Class':'Graduated', 'Name':'Alperen'}
print(dict['Name'])

Alperen


In [22]:
del dict['Name']
print(dict)
dict.clear()
print(dict)
del dict
print(dict['Age'])

{'Age': '24', 'Class': 'Graduated'}
{}


TypeError: ignored

#get, items

---

In [23]:
phoneboook = {'Chris':'555-1111','Katie':'555-222'}
value = phoneboook.get('Katie')
print(value)

555-222


In [24]:
phoneboook = {'Chris':'555-1111','Katie':'555-222','Joanne':'555-3333'}
for key, value in phoneboook.items():
  print(key,value)

Chris 555-1111
Katie 555-222
Joanne 555-3333


#NumPy
---

In [26]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

These codes are usual setup of NumPy 
we use ```warnings.filterwarnings("ignore")``` line to hide unnecessary warnings.

In [32]:
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [33]:
type(list1)

list

This was a list. We didn't use NumPy yet.

In [34]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

We converted the ```list1``` to a NumPy array. 

In [35]:
type(arr1)

numpy.ndarray

NumPy arrays' data type are "ndarray".

In [36]:
arr1.data

Array ```arr1```'s memory addres is writing above.

In [37]:
arr1.dtype

dtype('int64')

Array ```arr1```'s elements' data type is 'int64'.

In [38]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

We converted the ```arr1```'s elements to float from integer. 

In [39]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

array generation methods above.

In [43]:
arr2 = np.arange(0,10)
arr2.shape

(10,)

dimension of the ```arr2``` is above.

In [44]:
arr2.size

10

size (number of elements) of the ```arr2``` is above.

In [46]:
arr2.nbytes

80

number of bytes of the ```arr2``` is above.

In [47]:
len(arr2)

10

length of the ```arr2``` is above.

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [51]:
a = np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [52]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [53]:
arr1 = np.arange(1,20)
arr1[arr1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [54]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [55]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [57]:
np.random.random(4)

array([0.84650027, 0.81329426, 0.09280852, 0.42263816])

In [58]:
np.random.randint(0,500,5)

array([289, 230, 428, 447, 436])

In [59]:
np.random.randint(0,500,10)

array([164, 387, 289, 112, 120,  45, 373, 253, 480, 388])

In [63]:
np.random.seed(1998)
np.random.randint(0,500,5)

array([328, 161, 385, 160, 185])

In [64]:
np.random.seed(2022)
np.random.randint(0,500,5)

array([381, 220, 173, 112, 177])

In [65]:
f1 = np.random.uniform(5,10, size = (10))
f1

array([6.27655026, 5.89416138, 5.26626827, 5.39512176, 7.27998591,
       9.62028239, 7.20396298, 8.86962514, 6.50804098, 9.8130514 ])

In [66]:
np.floor(f1)

array([6., 5., 5., 5., 7., 9., 7., 8., 6., 9.])

In [67]:
np.trunc(f1)

array([6., 5., 5., 5., 7., 9., 7., 8., 6., 9.])

In [68]:
f1.astype(int)

array([6, 5, 5, 5, 7, 9, 7, 8, 6, 9])

In [70]:
b2 = np.random.randn(10)
b2

array([ 1.52751114, -1.91795951,  0.02607135,  0.74074879, -1.36606502,
        1.19379482,  0.91505233,  0.75164983, -1.47331479, -1.43911044])

normal distribution dataset above (average = 0, variance = 1)

In [80]:
arr1 = np.arange(10,61,10)
print(arr1)
for index, value in np.ndenumerate(arr1):
  print(index,value)

[10 20 30 40 50 60]
(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


Printing index of an array is above.

In [82]:
arr2 = np.arange(1,20)
print(arr2)
arr2.sum()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


190

Sum of an array is above.

In [83]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])


Cumulative sum of an array is above.

In [85]:
arr2.min()

1

In [86]:
arr2.max()

19

In [87]:
np.mean(arr2)

10.0

In [88]:
np.var(arr2)

30.0

In [90]:
np.median(arr2)

10.0

In [91]:
np.std(arr2)

5.477225575051661

### 2D arrays

In [92]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [93]:
np.amin(A,axis=0)

array([1, 2, 1, 0])

In [94]:
np.amin(A,axis=1)

array([0, 5, 1, 3])

for NumPy:
 - axis = 0 means coloumn
 - axis = 1 means row

In [95]:
for index, value in np.ndenumerate(A):
  print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [96]:
a = np.array ([7,5,3,9,0,2])

In [97]:
a[0]

7

In [98]:
a[1:4]

array([5, 3, 9])

In [99]:
a[-1]

2

In [100]:
a[-3:-1]

array([9, 0])

In [101]:
ar = np.arange(1,20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [102]:
rep1 = np.where(ar %2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [103]:
ar2 = np.array([10, 20 ,30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [107]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [108]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [110]:
np.put(p2, [0,3,5], [33,55,99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])